import style from "./page.module.css";
import Navbar from "./components/navbar";
import ChatList from "./components/chatlist";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const rootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body id={style.body} suppressHydrationWarning={true}>
        <Navbar />
        <ChatList />
        {children}
      </body>
    </html>
  );
};
export default rootLayout;
